const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  // _id will be automatically generated by MongoDB
  email: {
    type: String,
    required: true,
    unique: true,
  },
  checkinList: {
    type: [mongoose.Schema.Types.ObjectId], // Array of item IDs
    default: [],
  },
  checkoutList: {
    type: [mongoose.Schema.Types.ObjectId], // Array of item IDs
    default: [],
  },
  name: {
    type: String,
    required: true,
  },
  checkinCount: {
    type: Number,
    default: 0, // Initialize to 0
  },
  checkoutCount: {
    type: Number,
    default: 0, // Initialize to 0
  },
});

// Create the User model
const User = mongoose.model('User', userSchema);

module.exports = User; 